// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.onb.qms.domain;

import com.onb.qms.domain.VisitorDataOnDemand;
import com.torm.domain.Visitor;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect VisitorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VisitorDataOnDemand: @Component;
    
    private Random VisitorDataOnDemand.rnd = new SecureRandom();
    
    private List<Visitor> VisitorDataOnDemand.data;
    
    public Visitor VisitorDataOnDemand.getNewTransientVisitor(int index) {
        Visitor obj = new Visitor();
        setFirstName(obj, index);
        setLastName(obj, index);
        setMiddleName(obj, index);
        return obj;
    }
    
    public void VisitorDataOnDemand.setFirstName(Visitor obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void VisitorDataOnDemand.setLastName(Visitor obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public void VisitorDataOnDemand.setMiddleName(Visitor obj, int index) {
        String middleName = "middleName_" + index;
        obj.setMiddleName(middleName);
    }
    
    public Visitor VisitorDataOnDemand.getSpecificVisitor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Visitor obj = data.get(index);
        Long id = obj.getId();
        return Visitor.findVisitor(id);
    }
    
    public Visitor VisitorDataOnDemand.getRandomVisitor() {
        init();
        Visitor obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Visitor.findVisitor(id);
    }
    
    public boolean VisitorDataOnDemand.modifyVisitor(Visitor obj) {
        return false;
    }
    
    public void VisitorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Visitor.findVisitorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Visitor' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Visitor>();
        for (int i = 0; i < 10; i++) {
            Visitor obj = getNewTransientVisitor(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
