// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.onb.qms.domain;

import com.onb.qms.domain.VisitorDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VisitorDataOnDemand_Roo_Configurable {
    
    declare @type: VisitorDataOnDemand: @Configurable;
    
}
