// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.torm.domain;

import com.torm.domain.UserType;

privileged aspect UserType_Roo_JavaBean {
    
    public String UserType.getUsertype() {
        return this.usertype;
    }
    
    public void UserType.setUsertype(String usertype) {
        this.usertype = usertype;
    }
    
}
